---
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        network:
          assign_public_ip: true
        tags:
          Name: Ansible-Web-Server
      register: ec2

    - name: Display Public IP
      debug:
        msg: "EC2 Public IP: {{ ec2.instances[0].public_ip_address }}"
